backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true

site_url: https://lapicons.tk
display_url: https://lapicons.tk
logo_url: https://eroyx.tk/assets/images/cms.png

media_folder: "uploads"
collections:
  - label: "Category"
    name: "categories"
    folder: "_categories"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
        picker_utc: true
      - label: "Shortname"
        name: "name"
        widget: "string"
        required: true
        hint: "Ex: Two/three letter code."
      - label: "Display Name"
        name: "display_name"
        widget: "string"
        required: true
        hint: "Ex: Actuall name of the category."
      - label: "Category Color"
        name: "color-primary"
        widget: "color"
  - label: "Icons"
    name: "icons"
    folder: "_icons"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    delete: false
    editor:
      preview: false
      delete: false
    fields:
      - label: "Icon Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
        picker_utc: true
      - label: "Display Name"
        name: "display_name"
        widget: "string"
        required: true
        hint: "Ex: 1Password"
      - label: "Icon Shortcode"
        name: "name"
        widget: "string"
        required: true
        hint: "Ex: icon-1password"
      - label: "icon code"
        name: "code"
        widget: "string"
        required: true
        hint: "Ex: f1cb"
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        displayFields: ["display_name", "name"]
        searchFields: ["display_name", "name"]
        valueField: "name"